export const DEFAULT_APPROVAL_TEMPLATE_CODE_BY_BUSINESS_TYPE = {
  ARCHIVE_TEMPLATE: 'TARGET_ARCHIVE_TEMPLATE_REVIEW',
  STANDARD: 'TARGET_STANDARD_REVIEW',
  KNOWLEDGE: 'TARGET_KNOWLEDGE_REVIEW',
} as const;
