import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = (file: string) => readFileSync(resolve(process.cwd(), file), 'utf8')

describe('project overview and overlay contract', () => {
  it('renders scoped search, the Figma five-metric band and a normal list without actions', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    expect(overview).toContain("t('projects.scope.mine')")
    expect(overview).toContain("t('projects.scope.all')")
    expect(overview).toContain("id: 'amount'")
    expect(overview).toContain("tone: 'blue'")
    expect(overview).toContain("tone: 'green'")
    expect(overview).toContain("tone: 'orange'")
    expect(overview).toContain("tone: 'red'")
    expect(overview).toContain("filter: 'ACCEPTED_THIS_YEAR'")
    expect(overview).toContain('displayName(row)')
    expect(overview).not.toContain('archivedView')
    expect(overview).not.toContain(':title="t(\'common.action\')"')
    expect(overview).not.toContain('project:stage:update')
  })

  it('keeps the project table adaptive, single-line and uses the confirmed larger row size', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const table = source('src/design-system/BusinessTable.vue')
    expect(overview).toContain(':scroll="{ x: \'max-content\' }"')
    expect(overview).toContain('size="large"')
    expect(overview).toMatch(/:width="120"\s+fixed="left"/u)
    expect(overview).toContain("join(' · ') || '—'")
    expect(overview).toContain('fractionDigits: 2')
    expect(overview).toContain('table-layout: fixed !important')
    expect(overview).toContain('preserve-column-widths')
    expect(overview).toContain('flex-wrap: nowrap')
    expect(table).toContain('batchSize: 20')
    expect(table).toContain("size: 'large'")
    expect(table).toContain('white-space: nowrap')
    expect(table).toContain('width: max-content')
    expect(table).toContain('min-width: 100%')
    expect(table).toContain("emit('pageChange', nextPage)")
    expect(table).not.toContain('<a-pagination')
    expect(overview).not.toContain(':width="280"')
    expect(overview).toContain(':width="160"')
    expect(overview).toContain('summary-money.svg')
    expect(overview).toContain('toolbar-query.png')
    expect(overview).toContain("backgroundColor: '#d1fae5'")
    expect(overview).toContain("borderColor: '#a7f3d0'")
  })

  it('shows a password visibility control on the login form', () => {
    const login = source('src/views/login/index.vue')
    expect(login).toContain('class="password-visibility"')
    expect(login).toContain(":type=\"passwordVisible ? 'text' : 'password'\"")
    expect(login).toContain('IconEyeInvisible')
  })

  it('uses one Figma-aligned project detail dialog for create, edit and view', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    expect(overview).toContain("import ProjectDetailDialog from '../components/ProjectDetailDialog.vue'")
    expect(overview).toContain(':mode="drawerMode"')
    expect(overview).toContain('v-model:visible="projectDialogVisible"')
    expect(dialog).toContain('class="project-detail-dialog"')
    expect(dialog).toContain(':width="944"')
    expect(dialog).toContain('<h2>项目详情</h2>')
    expect(dialog).toContain("export type ProjectDetailDialogMode = 'create' | 'edit' | 'view'")
    expect(dialog).toContain('<ProjectPaymentPlan')
    expect(dialog).toContain('paymentPlans: plans')
    expect(dialog).toContain('合同名称')
    expect(dialog).toContain('档案模版')
    expect(dialog).not.toContain('purchaseOwnerId')
    expect(dialog).not.toContain('financeOwnerId')
  })

  it('keeps progress and payment data in the unified save payload', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    const paymentPlan = source('src/domains/project/components/ProjectPaymentPlan.vue')
    const api = source('src/domains/project/api/project.api.ts')
    expect(overview).toContain('v-model:visible="projectDialogVisible"')
    expect(dialog).toContain('deliveryStage: formData.deliveryStage')
    expect(dialog).toContain('progressPercent: formData.progressPercent')
    expect(dialog).toContain('paymentPlans: plans')
    expect(dialog).toContain('readonly = computed')
    expect(dialog).toContain(':on-before-cancel="beforeCancel"')
    expect(dialog).toContain('baseCurrencyCode')
    expect(overview).toContain("getFieldLabel('CURRENCY'")
    expect(overview).not.toContain('`CNY ${amount')
    expect(paymentPlan).toContain('props.baseCurrency')
    expect(paymentPlan).not.toContain("contractCurrency === 'CNY'")
    expect(api).toContain('/projects/${id}/progress')
    expect(api).not.toContain('/projects/${id}/stage')
    expect(api).not.toContain('/projects/${id}/acceptance')
  })

  it('keeps permanent deletion out of the Figma list while retaining the guarded API', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const api = source('src/domains/project/api/project.api.ts')
    expect(overview).not.toContain('row.canPermanentDelete')
    expect(overview).not.toContain('permanentDelete')
    expect(api).toContain('/projects/${id}/permanent')
  })
})
