import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const source = (file: string) => readFileSync(resolve(process.cwd(), file), 'utf8')

describe('project overview and overlay contract', () => {
  it('renders scoped search, the five-metric band and a normal list with Arco controls', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    expect(overview).toContain("t('projects.scope.mine')")
    expect(overview).toContain("t('projects.scope.all')")
    expect(overview).toContain("t('projects.scope.archived')")
    expect(overview).toContain("id: 'amount'")
    expect(overview.indexOf("id: 'amount'")).toBeLessThan(overview.indexOf("id: 'acceptedAmount'"))
    expect(overview.indexOf("id: 'acceptedAmount'")).toBeLessThan(overview.indexOf("id: 'total'"))
    expect(overview.indexOf("id: 'total'")).toBeLessThan(overview.indexOf("id: 'active'"))
    expect(overview.indexOf("id: 'active'")).toBeLessThan(overview.indexOf("id: 'accepted'"))
    expect(overview).not.toContain('summaryFilter')
    expect(overview).toContain('<article')
    expect(overview).toContain('<a-statistic')
    expect(overview).toContain('IconCheckCircle')
    expect(overview).toContain('IconLayers')
    expect(overview).toContain('IconPlayCircle')
    expect(overview).toContain('IconCalendarClock')
    expect(overview).toContain('IconUp')
    expect(overview).not.toContain('@/assets/figma/project-overview')
    expect(overview).toContain('<a-progress')
    expect(overview).toContain('<a-tag')
    expect(overview).toContain('<a-link class="project-link"')
    expect(overview).not.toContain('<button')
    expect(overview).toContain('displayName(row)')
    expect(overview).not.toContain('archivedView')
    expect(overview).toContain(':title="t(\'common.action\')"')
    expect(overview).not.toContain('project:stage:update')
  })

  it('keeps the project table adaptive, single-line and uses the confirmed larger row size', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const table = source('src/design-system/BusinessTable.vue')
    expect(overview).toContain(':scroll="{ x: \'max-content\' }"')
    expect(overview).toContain('size="large"')
    expect(overview).toMatch(/nameColumnWidth:\s*240/u)
    expect(overview).toMatch(/:width="projectLayout\.nameColumnWidth"\s+fixed="left"/u)
    expect(overview).toContain("join('·') || '-'")
    expect(overview).toContain('fractionDigits: 2')
    expect(overview).toContain('table-layout: fixed !important')
    expect(overview).toContain('preserve-column-widths')
    expect(overview).toContain('flex-wrap: nowrap')
    expect(table).toContain('batchSize: 20')
    expect(table).toContain("size: 'large'")
    expect(table).toContain('white-space: nowrap')
    expect(table).toContain('width: max-content')
    expect(table).toContain('min-width: 100%')
    expect(table).toContain("emit('pageChange', nextPage)")
    expect(table).not.toContain('<a-pagination')
    expect(overview).not.toContain(':width="280"')
    expect(overview).toContain(':width="160"')
    expect(overview).toContain('IconSearch')
    expect(overview).toContain('IconPlus')
    expect(overview).toContain('width: 28px')
    expect(overview).toContain('justify-content: flex-start')
    expect(overview).toContain('class="project-table-frame"')
    expect(overview).toContain("backgroundColor: '#d1fae5'")
    expect(overview).toContain("MYR: { color: '#10b981', backgroundColor: '#d1fae5' }")
    expect(overview).toContain(':width="80"')
    expect(overview).not.toContain('toolbar-refresh.png')
    expect(overview).toContain('grid-template-columns: repeat(4, 242px) minmax(0, 1fr)')
    expect(overview).toContain('grid-template-columns: repeat(5, minmax(0, 1fr))')
    expect(overview).toContain('flex: 1 1 auto')
  })

  it('shows a password visibility control on the login form', () => {
    const login = source('src/views/login/index.vue')
    expect(login).toContain('class="password-visibility"')
    expect(login).toContain(":type=\"passwordVisible ? 'text' : 'password'\"")
    expect(login).toContain('IconEyeInvisible')
  })

  it('uses one Figma-aligned shell with distinct form and read-only project detail structures', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    expect(overview).toContain(
      "import ProjectDetailDialog from '../components/ProjectDetailDialog.vue'",
    )
    expect(overview).toContain(':mode="drawerMode"')
    expect(overview).toContain('v-model:visible="projectDialogVisible"')
    expect(dialog).toContain('class="project-detail-dialog"')
    expect(dialog).toContain(':width="1040"')
    expect(dialog).toContain('<h2>项目详情</h2>')
    expect(dialog).toContain("export type ProjectDetailDialogMode = 'create' | 'edit' | 'view'")
    expect(dialog).toContain('v-else-if="renderView"')
    expect(dialog).toContain('class="project-detail-view"')
    expect(dialog).toContain('class="project-detail-form"')
    expect(dialog).toContain('<ProjectPaymentPlan')
    expect(dialog).toContain('v-if="canEditProject"')
    expect(dialog).toContain('@click="emit(\'edit\')"')
    expect(dialog).toContain('编辑项目')
    expect(dialog).not.toContain('<button')
    expect(dialog).toContain('paymentPlans: plans')
    expect(dialog).toContain('合同名称')
    expect(dialog).toContain('档案模版')
    expect(dialog).not.toContain('purchaseOwnerId')
    expect(dialog).not.toContain('financeOwnerId')
  })

  it('keeps progress and payment data in the unified save payload', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    const paymentPlan = source('src/domains/project/components/ProjectPaymentPlan.vue')
    const api = source('src/domains/project/api/project.api.ts')
    expect(overview).toContain('v-model:visible="projectDialogVisible"')
    expect(dialog).toContain('deliveryStages: [...formData.deliveryStages]')
    expect(dialog).toContain('v-model="formData.deliveryStages"')
    expect(dialog).toContain('multiple')
    expect(dialog).toContain('progressPercent: formData.progressPercent')
    expect(dialog).toContain('actualAcceptanceAt: canEditAcceptance.value')
    expect(dialog).toContain('paymentPlans: plans')
    expect(dialog).toContain('readonly = computed')
    expect(dialog).toContain('.filter((item) => item.enabled || item.value === currentValue)')
    expect(dialog).toContain('disabled: !item.enabled')
    expect(dialog).toContain('fieldConfig.isFieldRequired')
    expect(dialog).toContain('项目字段配置加载失败')
    expect(dialog).toContain(':mask-closable="false"')
    expect(dialog).toContain(':esc-to-close="false"')
    expect(dialog).toContain("okText: '保存'")
    expect(dialog).toContain("cancelText: '放弃修改'")
    expect(dialog).toContain('payload.acceptedConvertedAmount = formData.acceptedConvertedAmount')
    expect(dialog).toContain('return option.displayName')
    expect(dialog).not.toContain('option.name)')
    expect(dialog).toContain('baseCurrencyCode')
    expect(overview).toContain("configuredOption('CURRENCY'")
    expect(overview).toContain("t('projects.columns.contractCurrency')")
    expect(overview).toContain('projectManager:asc')
    expect(overview).toContain('projectManager:desc')
    expect(overview).not.toContain('`CNY ${amount')
    expect(paymentPlan).toContain('props.baseCurrency')
    expect(paymentPlan).toContain('width: max-content')
    expect(paymentPlan).toContain('overflow-x: scroll')
    expect(paymentPlan).toContain(':bordered="{ wrapper: true, cell: true }"')
    expect(paymentPlan).not.toContain(':scroll="{ x: 1083 }"')
    expect(paymentPlan).not.toContain("contractCurrency === 'CNY'")
    expect(api).toContain('/projects/${id}/progress')
    expect(api).not.toContain('/projects/${id}/stage')
    expect(api).not.toContain('/projects/${id}/acceptance')
  })

  it('routes the permission-gated view action into the shared edit dialog', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    const permissionCatalog = source(
      '../delivery-platform-server/src/modules/permission/permission-catalog.ts',
    )
    const permissions = source('../delivery-platform-server/prisma/seed-data/permissions.ts')

    expect(overview).toContain('@edit="editProject"')
    expect(overview).toContain('path: `/projects/${drawerProjectId.value}/edit`')
    expect(dialog).toContain("hasPermission('project:update')")
    expect(permissionCatalog).toContain("pageName: '项目概览'")
    expect(permissionCatalog).toContain("pageName: '款项计划'")
    expect(permissions).toContain("permissionName: '编辑项目'")
    expect(permissions).toContain("permissionName: '修改项目进度'")
    expect(permissions).toContain("permissionName: '编辑款项计划'")
  })

  it('keeps project and payment scrollbars visible and payment amount-ratio editing linked', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const dialog = source('src/domains/project/components/ProjectDetailDialog.vue')
    const paymentPlan = source('src/domains/project/components/ProjectPaymentPlan.vue')

    expect(overview).toContain('<span class="cell-center nowrap">{{ region(row) }}</span>')
    expect(overview).toMatch(/business-table__viewport\)[^{]*\{[^}]*overflow:\s*scroll;/su)
    expect(dialog).toMatch(/\.dialog-body\s*\{[^}]*overflow-y:\s*scroll;/su)
    expect(paymentPlan).toContain('label="付款金额（按合同币种）"')
    expect(paymentPlan).toContain('label="付款比例"')
    expect(paymentPlan).toContain("lastEditedField.value = 'amount'")
    expect(paymentPlan).toContain("lastEditedField.value = 'ratio'")
    expect(paymentPlan).toContain('moneyFromPercent(form.paymentRatio')
    expect(paymentPlan).toContain('percentValue(form.originalAmount')
    expect(paymentPlan).toContain('overflow-x: scroll')
    expect(paymentPlan).toContain('<span class="payment-cell-left">{{ converted(record) }}</span>')
  })

  it('exposes safe project deletion for every server-authorized administrator list row', () => {
    const overview = source('src/domains/project/pages/ProjectOverviewPage.vue')
    const api = source('src/domains/project/api/project.api.ts')
    expect(overview).toContain('v-if="row.canDelete"')
    expect(overview).toContain('@click="deleteProject(row)"')
    expect(overview).toContain("content: t('projects.deleteConfirm', { name: project.projectName })")
    expect(overview).toContain('Promise.all([listQuery.refetch(), summaryQuery.refetch()])')
    expect(overview).toContain(
      "error instanceof Error && error.message ? error.message : t('projects.deleteFailed')",
    )
    expect(api).toContain('request.delete<void>(`/projects/${id}`, { silent: true })')
  })
})
