import type { Level1Def, Level2Def } from './archive-templates';

const stage01 = '01_sale';
const stage02 = '02_design';
const stage03 = '03_procurement';

const s01L1s: Level1Def[] = [
  { stageCode: stage01, itemNo: 1, level: 1, name: '项目立项资料', responsibleRole: 'PROJECT_MANAGER' },
  {
    stageCode: stage01,
    itemNo: 2,
    level: 1,
    name: '售前方案与节能测算',
    isStar: true,
    needReview: true,
    responsibleRole: 'PROJECT_MANAGER',
    reviewRole: 'DELIVERY_MANAGER',
  },
  {
    stageCode: stage01,
    itemNo: 3,
    level: 1,
    name: '项目成本预算（售前版）',
    isSensitive: true,
    isStar: true,
    responsibleRole: 'PROJECT_MANAGER',
  },
  {
    stageCode: stage01,
    itemNo: 4,
    level: 1,
    name: '项目报价清单',
    isSensitive: true,
    usageDescription: '上传对客户的报价清单、报价依据、版本说明以及内部审批记录。',
  },
  {
    stageCode: stage01,
    itemNo: 5,
    level: 1,
    name: '招投标相关文件',
    usageDescription: '上传招标文件、答疑文件、投标澄清、评标沟通记录等资料。',
  },
  {
    stageCode: stage01,
    itemNo: 6,
    level: 1,
    name: '投标文件或提交方案',
    isStar: true,
  },
  {
    stageCode: stage01,
    itemNo: 7,
    level: 1,
    name: '中标通知书',
    isStar: true,
    allowedFileTypes: 'pdf,jpg,jpeg,png',
  },
  {
    stageCode: stage01,
    itemNo: 8,
    level: 1,
    name: '项目合同（盖章扫描件）',
    isStar: true,
    isSensitive: true,
    needReview: true,
    responsibleRole: 'PROJECT_MANAGER',
    reviewRole: 'DELIVERY_MANAGER',
    allowedFileTypes: 'pdf',
  },
];

const s01L2s: Level2Def[] = [
  {
    stageCode: stage01,
    parentItemNo: 1,
    itemNo: 1001,
    level: 2,
    name: '商机评估表',
    secondName: '商机评估表',
    usageDescription: '上传商机来源、客户诉求、收益判断、风险判断和是否立项的评估记录。',
  },
  {
    stageCode: stage01,
    parentItemNo: 1,
    itemNo: 1002,
    level: 2,
    name: '客户需求记录',
    secondName: '客户需求记录',
    usageDescription: '上传客户访谈纪要、需求清单、现场调研记录、图片或视频说明。',
  },
  {
    stageCode: stage01,
    parentItemNo: 1,
    itemNo: 1003,
    level: 2,
    name: '项目启动会纪要',
    secondName: '项目启动会纪要',
    usageDescription: '上传启动会签到、会议纪要、任务分工和关键里程碑确认材料。',
  },
  {
    stageCode: stage01,
    parentItemNo: 1,
    itemNo: 1004,
    level: 2,
    name: '商务沟通记录',
    secondName: '商务沟通记录',
    usageDescription: '上传合同条款、付款节点、范围边界、客户确认等商务沟通记录。',
  },
  {
    stageCode: stage01,
    parentItemNo: 1,
    itemNo: 1005,
    level: 2,
    name: '售前风险清单',
    secondName: '售前风险清单',
    usageDescription: '上传售前阶段识别的技术、商务、交付和安全风险清单。',
  },
  {
    stageCode: stage01,
    parentItemNo: 2,
    itemNo: 2001,
    level: 2,
    name: '售前技术方案',
    secondName: '售前技术方案',
  },
  {
    stageCode: stage01,
    parentItemNo: 2,
    itemNo: 2002,
    level: 2,
    name: '节能测算表',
    secondName: '节能测算表',
    usageDescription: '上传节能测算书、测算依据、历史数据、运行报表和边界条件说明。',
  },
  {
    stageCode: stage01,
    parentItemNo: 2,
    itemNo: 2003,
    level: 2,
    name: '调研资料',
    secondName: '调研资料',
    usageDescription: '上传现场照片、CAD 图纸、设备铭牌、调研表和数据采集记录。',
  },
  {
    stageCode: stage01,
    parentItemNo: 8,
    itemNo: 8001,
    level: 2,
    name: '盖章扫描件',
    secondName: '盖章扫描件',
    usageDescription: '上传项目合同 PDF、补充协议、无合同交付流程审批和启动会确认记录。',
  },
];

const s02L1s: Level1Def[] = [
  {
    stageCode: stage02,
    itemNo: 9,
    level: 1,
    name: '项目实施计划表',
    usageDescription: '上传进度计划、资源计划、关键节点、客户配合条件和风险缓解计划。',
  },
  {
    stageCode: stage02,
    itemNo: 10,
    level: 1,
    name: '施工方案（深化版）',
    usageDescription: '上传设计院图纸、甲方图纸、施工图、施工方案、策划书和施工指导文件。',
  },
  {
    stageCode: stage02,
    itemNo: 11,
    level: 1,
    name: '系统设计（深化版）',
    isStar: true,
    usageDescription: '上传系统原理图、PID 图、网络拓扑、I/O 点表和接口边界说明。',
  },
  {
    stageCode: stage02,
    itemNo: 12,
    level: 1,
    name: '硬件设计（深化版）',
    isStar: true,
    usageDescription: '上传柜体图纸、柜内原理图、电缆清册、接线表和材料清单。',
  },
  {
    stageCode: stage02,
    itemNo: 13,
    level: 1,
    name: '软件设计（深化版）',
    isStar: true,
    usageDescription: '上传软件功能清单、画面清单、点表、接口清单和版本说明。',
  },
  {
    stageCode: stage02,
    itemNo: 14,
    level: 1,
    name: '项目成本预算（深化版）',
    isStar: true,
    isSensitive: true,
    needReview: true,
    responsibleRole: 'PROJECT_MANAGER',
    reviewRole: 'DELIVERY_MANAGER',
    usageDescription: '上传项目总预算、柜体清单、主材清单、施工清单、分包预算和版本说明。',
  },
  {
    stageCode: stage02,
    itemNo: 15,
    level: 1,
    name: '深化方案评审记录表',
    needReview: true,
    reviewRole: 'DELIVERY_MANAGER',
    usageDescription: '上传评审会议纪要、评审问题清单、整改关闭记录和审批 PDF。',
  },
];

const s02L2s: Level2Def[] = [
  { stageCode: stage02, parentItemNo: 10, itemNo: 10001, level: 2, name: '深化版施工方案', secondName: '深化版施工方案' },
  { stageCode: stage02, parentItemNo: 11, itemNo: 11001, level: 2, name: '系统设计资料', secondName: '系统设计资料' },
  { stageCode: stage02, parentItemNo: 12, itemNo: 12001, level: 2, name: '硬件设计资料', secondName: '硬件设计资料' },
  { stageCode: stage02, parentItemNo: 13, itemNo: 13001, level: 2, name: '软件设计资料', secondName: '软件设计资料' },
  { stageCode: stage02, parentItemNo: 14, itemNo: 14001, level: 2, name: '深化成本预算', secondName: '深化成本预算' },
];

const s03L1s: Level1Def[] = [
  {
    stageCode: stage03,
    itemNo: 16,
    level: 1,
    name: '采购申请与设备清单',
    usageDescription: '上传采购申请、设备选型、数量清单、到货计划和采购审批记录。',
  },
  {
    stageCode: stage03,
    itemNo: 17,
    level: 1,
    name: '分包管理',
    isSensitive: true,
    needReview: true,
    reviewRole: 'PROJECT_MANAGER',
  },
  {
    stageCode: stage03,
    itemNo: 18,
    level: 1,
    name: '供应商报价与比选',
    usageDescription: '上传供应商报价、技术澄清、比价表、选型理由和审批记录。',
  },
  {
    stageCode: stage03,
    itemNo: 19,
    level: 1,
    name: '设备生产与出厂计划',
    usageDescription: '上传生产进度、出厂检验计划、发货计划和设备资料交付清单。',
  },
];

const s03L2s: Level2Def[] = [
  {
    stageCode: stage03,
    parentItemNo: 17,
    itemNo: 17001,
    level: 2,
    name: '施工分包',
    secondName: '施工分包',
    usageDescription: '上传施工分包合同、付款节点、签证单、结算依据和项目经理确认记录。',
  },
  {
    stageCode: stage03,
    parentItemNo: 17,
    itemNo: 17002,
    level: 2,
    name: '柜体分包',
    secondName: '柜体分包',
    usageDescription: '上传柜体分包合同、图纸确认、出厂检验和交付清单。',
  },
  {
    stageCode: stage03,
    parentItemNo: 17,
    itemNo: 17003,
    level: 2,
    name: '设备分包',
    secondName: '设备分包',
    usageDescription: '上传设备合同、技术协议、到货计划、验收记录和售后联系信息。',
  },
];

export const earlyLevel1Defs: Level1Def[] = [...s01L1s, ...s02L1s, ...s03L1s];
export const earlyLevel2Defs: Level2Def[] = [...s01L2s, ...s02L2s, ...s03L2s];
