import type { PrismaClient } from '@prisma/client';

export async function seedCountries(prisma: PrismaClient) {
  const countries = [
    {
      countryCode: 'CN',
      nameZh: '中国',
      nameEn: 'China',
      defaultLanguage: 'zh-CN',
      defaultCurrency: 'CNY',
      timezone: 'Asia/Shanghai',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: null,
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'VN',
      nameZh: '越南',
      nameEn: 'Vietnam',
      defaultLanguage: 'vi-VN',
      defaultCurrency: 'VND',
      timezone: 'Asia/Ho_Chi_Minh',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: '需要商务签证，提前2周申请',
      safetyNotes: null,
      taxNotes: '增值税10%',
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'TH',
      nameZh: '泰国',
      nameEn: 'Thailand',
      defaultLanguage: 'th-TH',
      defaultCurrency: 'THB',
      timezone: 'Asia/Bangkok',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: '需工作许可',
      safetyNotes: null,
      taxNotes: '增值税7%',
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'MY',
      nameZh: '马来西亚',
      nameEn: 'Malaysia',
      defaultLanguage: 'ms-MY',
      defaultCurrency: 'MYR',
      timezone: 'Asia/Kuala_Lumpur',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: null,
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'ID',
      nameZh: '印度尼西亚',
      nameEn: 'Indonesia',
      defaultLanguage: 'id-ID',
      defaultCurrency: 'IDR',
      timezone: 'Asia/Jakarta',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: null,
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'SG',
      nameZh: '新加坡',
      nameEn: 'Singapore',
      defaultLanguage: 'en-US',
      defaultCurrency: 'SGD',
      timezone: 'Asia/Singapore',
      weekendRule: 'Saturday-Sunday',
      entryRequirements: null,
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'OM',
      nameZh: '阿曼',
      nameEn: 'Oman',
      defaultLanguage: 'ar-OM',
      defaultCurrency: 'OMR',
      timezone: 'Asia/Muscat',
      weekendRule: 'Friday-Saturday',
      entryRequirements: '需签证，遵守当地法规',
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
    {
      countryCode: 'AE',
      nameZh: '阿联酋',
      nameEn: 'UAE',
      defaultLanguage: 'ar-OM',
      defaultCurrency: 'USD',
      timezone: 'Asia/Dubai',
      weekendRule: 'Friday-Saturday',
      entryRequirements: null,
      safetyNotes: null,
      taxNotes: null,
      paymentNotes: null,
      supplierNotes: null,
      status: 'Active',
    },
  ];

  for (const country of countries) {
    await prisma.country.upsert({
      where: { countryCode: country.countryCode },
      update: {},
      create: country,
    });
  }

  console.log(`Seeded ${countries.length} countries`);
}
