ALTER TABLE `permissions`
  ADD COLUMN `deprecated_at` DATETIME(3) NULL;

CREATE INDEX `permissions_deprecated_at_idx`
  ON `permissions`(`deprecated_at`);

UPDATE `permissions`
SET `deprecated_at` = CURRENT_TIMESTAMP(3)
WHERE `deprecated_at` IS NULL
  AND `permission_code` IN (
    'approval:manage',
    'approval:view',
    'archive:delete',
    'archive:generate',
    'archive:mark_not_applicable',
    'archive:review',
    'archive:update',
    'archive:view_statistics',
    'archive_template:delete',
    'archive_template:update',
    'attachment:delete',
    'attachment:download',
    'attachment:upload',
    'attachment:view',
    'checklist:create',
    'checklist:delete',
    'checklist:review',
    'checklist:submit',
    'checklist:update',
    'checklist:view',
    'checklist:view_statistics',
    'country:create',
    'country:delete',
    'country:update',
    'country:view',
    'currency:create',
    'currency:delete',
    'currency:update',
    'file:delete',
    'file:review',
    'file:set_current',
    'file:upload',
    'file:view',
    'knowledge:delete',
    'knowledge:operate',
    'knowledge:update',
    'knowledge:upload',
    'language:create',
    'language:delete',
    'language:update',
    'language:view',
    'notification:create',
    'notification:manage_rules',
    'notification:view',
    'okr:create',
    'okr:delete',
    'okr:download',
    'okr:operate',
    'okr:score',
    'okr:update',
    'okr:upload',
    'okr:view',
    'okr:view_team',
    'process_record:download',
    'process_record:operate',
    'process_record:upload',
    'process_record:view',
    'project:view_cost',
    'report:create',
    'report:delete',
    'report:download',
    'report:operate',
    'report:review',
    'report:submit',
    'report:update',
    'report:upload',
    'report:view',
    'retrospective:manage',
    'retrospective:view',
    'skill:manage',
    'skill:view',
    'system:manage_backup',
    'system:manage_config',
    'system:view_log',
    'system:view_storage',
    'template:create',
    'template:delete',
    'template:download',
    'template:operate',
    'template:publish',
    'template:update',
    'template:upload',
    'template:view',
    'todo:view',
    'tools:create',
    'tools:delete',
    'tools:update',
    'training:download',
    'training:manage',
    'training:upload',
    'training:view',
    'workflow:create',
    'workflow:delete',
    'workflow:download',
    'workflow:operate',
    'workflow:update',
    'workflow:upload',
    'workflow:view'
  );

UPDATE `users`
SET `permission_version` = `permission_version` + 1
WHERE `deleted_at` IS NULL;
